### ISSUE TITLE
Fast implementation of Fractal Compression

### ISSUE THREAD

**Issue by jinankjain** [kennberg/fractal-compression#1]
Hi Alex,

We were on working on Fractal Compression for one of our course project. We took your code as a reference code tried making a faster version of fractal compression on single core using vector intrinsics and doing some  cache optimizations. 

We are happy to inform you that we were able to achieve a speed up of around 14x on a single core.
Link to our repository: https://github.com/xabarass/fast-fractal-compression
Project Report with some details about the implementation: https://github.com/xabarass/fast-fractal-compression/blob/master/report-06.pdf

Thanks,
Jinank Jain

**Comment by kennberg** [comment]
Thank you for the note. I read the paper. Good work on improving performance. I should reference it in my readme.

**Comment by jinankjain** [comment]
Thanks @kennberg
